F5Networks/f5-ci-docs

docs/_templates/layout.html
@amudukutore 
Fixes #316
I added a link to DevCentral (with the filter "containers") to the bottom of the sidebar.
See screenshot below to see how the link looks in the sidebar.
We agreed offline that it would be nice to make it easier for customers looking at clouddocs to find articles on DC that cover similar topics. I used the search filter "containers" to cast the widest possible net for related content.
=> Add link to devcentral to sidebar

docs/conf.py, docs/kubernetes/config_examples/f5-k8s-bigip-ctlr_image-secret.yaml, docs/kubernetes/config_examples/f5-k8s-sample-rbac.yaml, docs/marathon/mctlr-authenticate-dcos.rst
Problem: The service account name for the controller in the RBAC setup was inconsistent across
examples. This caused confusion in someone using our documentation.
Solution: Adjust the config examples to use "bigip-ctlr" as the service account name, which is what we use when initially creating the account.
Also updated some broken links.
Fixes #321
=> Make bigip-ctlr service account name consistent

docs/openshift/kctlr-openshift-routes.rst
Problem: Line highlighting for route controller config was highlighting the wrong lines.
Solution: Update the highlighting to point at the route-specific config parameters.
Fixes #323
=> Fix highlighting for route controller config

docs/releases_and_versioning.rst
@amudukutore 
Fixes #326 
Updates the marathon-bigip-ctlr versioning table to indicate the versions 1.1.1+ are supported for use with newer versions of mesos & marathon.
=> Fixes #326 - update releases and versioning table

.travis.yml, docs/kubernetes/config_examples/f5-k8s-bigip-ctlr_image-secret.yaml, docs/kubernetes/kctlr-ingress.rst
With the addition of the new Default IP for Ingress feature, it's important to document the different
ways in which VIPs can be configured for Ingresses.
Documentation has been added to mention the ways in which the IP  can be set, via annotation,
DNS lookup, or the default ip configuration parameter for the controller.
=> Ingress IP specifications

docs/_static/reuse/k8s-version-added-1_4.rst, docs/conf.py, docs/kubernetes/config_examples/f5-k8s-bigip-ctlr_image-secret.yaml, docs/kubernetes/config_examples/f5-k8s-ingress-fanout.yaml, docs/kubernetes/config_examples/f5-k8s-ingress-health-monitor.yaml, docs/kubernetes/config_examples/f5-k8s-ingress-tls-secret.yaml, docs/kubernetes/config_examples/f5-k8s-ingress-tls.yaml, docs/kubernetes/config_examples/f5-k8s-ingress-virtual-hosting.yaml, docs/kubernetes/config_examples/f5-k8s-ingress-virtual-hosting_all.yaml, docs/kubernetes/config_examples/f5-k8s-single-ingress.yaml, docs/kubernetes/config_examples/f5-resource-pool-only-example.configmap.yaml, docs/kubernetes/config_examples/f5-resource-vs-example.configmap.yaml, docs/kubernetes/config_examples/f5-resource-vs-example.json, docs/kubernetes/config_examples/f5-resource-vs-iApp-example.configmap.yaml, docs/kubernetes/config_examples/f5-resource-vs-iApp-example.json, docs/kubernetes/kctlr-app-install.rst, docs/kubernetes/kctlr-ingress.rst, docs/kubernetes/kctlr-manage-bigip-objects.rst
@sjberman 
Fixes #319 
- Edit Ingress default IP docs; fix up and clarify Ingress examples
- ensure consistency across examples -- partition name, schema version
View the [staged documentation](https://s3-us-west-2.amazonaws.com/staging-c2ub89n2qjgt1/f5-ci-docs/pr328/kubernetes/kctlr-ingress.html).
Linkcheck will fail the build in travis -- contains a link to product docs for v1.4 that don't exist online yet.
=> Ingress IP docs -- edits complete

.travis.yml, docs/conf.py
@sjsharma2001 @amudukutore 
Fixes #338 
- Add `rst_prolog` with a javascript redirect to let users switch from 'v1' to 'latest'
- update branch allowed for deployment to 'v1-eol'
See staging site for example: https://s3-us-west-2.amazonaws.com/staging-c2ub89n2qjgt1/test/v1/openshift/index.html
=> Fixes #338

docs/marathon/config_examples/f5-marathon-bigip-ctlr-example.json, docs/marathon/mctlr-authenticate-dcos.rst
Modified the example for the F5_CC_DCOS_AUTH_CREDENTIALS, which is tricky
because the quotes in the JSON blob and the newlines in the private key
need to be escaped.
Fixes #356.
=> Clarified authentication setup for DC/OS Enterprise

docs/cloudfoundry/cf-per-route-virtuals.rst, docs/cloudfoundry/config_examples/manifest.yaml, docs/conf.py
Problem:
Current Cloud Foundry documentation had an incorrect
SERVICE_BROKER_CONFIG example in its manifest that needed to be
corrected. Also some of the documentation on the tier2_ip_range
configuration parameter needed a little bit more background information
to help users to set it up properly.
Solution:
Correct the incorrect SERVICE_BROKER_CONFIG example and add links and a
warning to call out how to properly set the tier2_ip_range parameter.
Fixes: #367
=> Updating cf controller documentation.

docs/kubernetes/kctlr-use-bigip-k8s.rst
@f5yacobucci 
Fixes #373
WIP #<issueid>
...
Fixes #373 -- clarifies that the BIG-IP node status will always be NotReady 
view changes inline
I did include this update in the PR for #314, but I wanted to get this critical fix out there now since that PR is still a WIP.
=> Fixes #373

docs/conf.py
Correct site name -- "Container Integrations" --> "Container Connectors"
@<reviewer_id>
WIP #<issueid>
...
The name "Container Integrations" is not correct (since the removal of the ASP content, only Container Connectors docs live here). The site is renamed to Container Connectors to accurately reflect the product naming.
=> Correct html_title 

docs/conf.py, docs/kubernetes/index.rst, docs/kubernetes/kctlr-app-install.rst, docs/kubernetes/kctlr-ingress.rst, docs/openshift/index.rst, docs/openshift/kctlr-openshift-app-install.rst
- updated k8s index and install to reference helm chart for controller and link to stable f5networks/charts.
- updates openshift index and install in same manner.
- updated the kctlr-ingress document to reference the ingress chart and to clarify that the ctlr chart and ingress chart are independent.
- added links to conf.py
=> Add references and links for helm charts

docs/openshift/kctlr-openshift-bigip-ha.rst
What issues does this address?
When you are using different Route Domains you need to add the implicit "remote-address any" otherwize tmsh asummes it's from the Route domain 0 and gives an error.
Environment
*  OpenShift with multiple route domains
Updates the OpenShift BIG-IP HA doc with information about route domains.
=> The instructions fails on other routedomain than 0

docs/kubernetes/kctlr-modes.rst
@jputrino 
typo in text.  Diagram does not match text.
=> fix text to match diagram per feedback from Austin P.

docs/marathon/index.rst, docs/openshift/kctlr-openshift-routes.rst
Fixes #417 
Fixes a formatting issue that caused the `|kctlr|` substitution to show up in the live documentation.
Fixes a broken link that caused the build to fail.
=> Fixes #417 - sphinx substitution showing up in live docs

docs/releases_and_versioning.rst
there was field confusion about whether the BIG-IP controller for OpenShift was supported because the beginning of the page did not explicitly mention it.
----------
----------
@<reviewer_id>
WIP #<issueid>
...
=> added line for BIG-IP Controller for OpenShift

docs/troubleshooting/kubernetes.rst, docs/troubleshooting/openshift.rst
----------
----------
@jputrino
Fixes #435 
WIP #<issueid>
...
Corrects the method to put the controller into debug mode
Per an email exhange between myself and Ryan Talley the controller does not support this annotation so the only way to put it into debug mode is by adding the arg and re-deploying.
=> fix for #435

docs/releases_and_versioning.rst
Adding OpenShift v3.11x to k8s-bigip-ctlr v1.7x section of the release and versioning matrix.
=> Adding OpenShift v3.11x to the release and versioning matrix

docs/releases_and_versioning.rst
Adding OpenShift v3.11x to the release and versioning martrix.
This commit moves changes from staging (master) to the live site (v2).
=> Adding OpenShift v3.11x to the release and versioning martrix

docs/troubleshooting/openshift.rst
Update the VLAN and VXLAN names for the examples at lines 191 and 208. The one at 191 was incorrect. It had the example name of the overlay VXLAN Tunnel and it needed to be the underlay VLAN for the VXLAN tunnel. On line 208 I updated the text of the example name to match the example names used later in the doc.
----------
----------
@<reviewer_id>
WIP #<issueid>
...
=> Update VLAN and VXLAN example names

docs/kubernetes/config_examples/f5-k8s-sample-rbac.yaml
Line 31 the value should be "" instead of rbac.authorization.k8s.io. From issue:
https://github.com/F5Networks/k8s-bigip-ctlr/issues/938
=> Update apiGroup syntax
