F5Networks/f5-ci-docs

- docs/acknowledgements.rst
- docs/conf.py
Fixes #329 
- Updates the project copyright
- Fixes a broken link in the acknowledgments doc
> Fixes #329

- README.rst
@<reviewer_id>
Fixes # N/A
WIP #<issueid>
...
Fixes display of the travis badge in GitHub.
> fix travis badge

- docs/_static/reuse/bigip-admin-permissions-reqd.rst
- docs/cloudfoundry/cfctlr-app-install.rst
- docs/conf.py
- docs/kubernetes/config_examples/f5-k8s-bigip-ctlr_image-secret.yaml
- docs/kubernetes/config_examples/f5-kctlr-bigip-node.yaml
- docs/kubernetes/flannel-bigip-info.rst
- docs/kubernetes/index.rst
- docs/kubernetes/kctlr-app-install.rst
- docs/kubernetes/kctlr-deploy-iapp.rst
- docs/kubernetes/kctlr-ingress.rst
- docs/kubernetes/kctlr-manage-bigip-objects.rst
- docs/kubernetes/kctlr-modes.rst
- docs/kubernetes/kctlr-use-bigip-k8s.rst
- docs/marathon/config_examples/f5-marathon-bigip-ctlr-example.json
- docs/marathon/index.rst
- docs/marathon/mctlr-app-install.rst
- docs/marathon/mctlr-authenticate-dcos.rst
- docs/marathon/mctlr-deploy-iapp.rst
- docs/master_toc.rst
- docs/openshift/config_examples/f5-kctlr-openshift-hostsubnet.yaml
- docs/openshift/config_examples/f5-kctlr-openshift-routes.yaml
- docs/openshift/kctlr-openshift-routes.rst
- docs/openshift/kctlr-use-bigip-openshift.rst
- docs/openshift/replace-f5-router.rst
- docs/troubleshooting/openshift.rst
@chen23 @russokj @nmenant @f5yacobucci 
Fixes #347
Fixes #349 
Fixes #352 
Fixes #353 
Fixes #354 
Fixes #355 
Fixes #360 
This PR contains fixes for a series of high-priority bugs, listed above. In summary:
- provide `--flannel-name` in config examples
- fix highlighting in config examples
- clarify flannel/BIG-IP integration overview
- clarify flannel/BIG-IP setup doc 
- clarify openshift SDN/BIG-IP setup doc
View changes inline below or see [staged documentation](https://s3-us-west-2.amazonaws.com/staging.clouddocs.f5.com/containers/pr351/index.html)
> Critical bugfixes

- docs/drafts/source-address-translation-config.rst
Problem:
Virtual server source address translation configuration needs to be
added to the solution docs.
Solution:
Add draft for it to the solution docs.
----------
----------
@<reviewer_id>
WIP #<issueid>
...
> Add snat config draft.

- docs/kubernetes/kctlr-modes.rst
- docs/openshift/kctlr-openshift-bigip-ha.rst
@<reviewer_id>
Fixes #415 
Fixes a mismatch between diagram and text.
> Update v2 with bugfix from master

- .travis.yml
I wasn't able to resolve the travis error that occurred when it tried to run the deploy script. Instead, I switched to using the built-in travis s3 deployment. This should be changed back when the travis issue is resolved.
----------
----------
@<reviewer_id>
WIP #<issueid>
...
> Fix travis build error (#424)

- docs/troubleshooting/kubernetes.rst
- docs/troubleshooting/openshift.rst
* Fix for #435
* fixes for #435
----------
----------
@<reviewer_id>
WIP #<issueid>
...
> fix for #435 (#436)

- docs/troubleshooting/kubernetes.rst
- docs/troubleshooting/openshift.rst
- requirements.txt
@<reviewer_id>
WIP #<issueid>
N/A
Add f5-sphinx-theme version requirement to release branch
> Merge master into v2

- docs/releases_and_versioning.rst
> updated for 1.7.1 kubernetes fix

- .travis.yml
- docs/releases_and_versioning.rst
----------
----------
@<reviewer_id>
WIP #<issueid>
...
> correct 1.9 to 1.9.x

- docs/kubernetes/kctlr-k8s-as3.rst
Begin new section for CIS service discovery.
> Add Service Discovery Section

- docs/kubernetes/kctlr-k8s-as3.rst
----------
----------
@<reviewer_id>
WIP #<issueid>
...
> Adding examples

- docs/kubernetes/kctlr-k8s-as3.rst
> fix broken header

- docs/kubernetes/kctlr-k8s-as3.rst
Fix broken yaml download link.
> fix yaml link

- docs/kubernetes/kctlr-k8s-as3.rst
> add more code entries

- docs/kubernetes/kctlr-k8s-as3.rst
----------
----------
@<reviewer_id>
WIP #<issueid>
...
> fix broken table

- docs/cloudfoundry/cfctlr-app-install.rst
- docs/kubernetes/index.rst
Rebranding Container Connectors to Controller Ingress Services.
> Change CC to CIS

- docs/conf.py
Change breadcrumb path from 'container connectors to container ingress services.
> modify breadcrumb

- Makefile
- make.bat
Changing instances of CC to CIS for the 1.9 release.
> Update for 1.9

- docs/conf.py
- docs/index.rst
1.9 rebrand effort. From Container Connector to Container Ingress Services.
> update for rebrand to CIS

- docs/kubernetes/kctlr-k8s-as3.rst
> create ssl draft

- docs/kubernetes/kctlr-k8s-as3.rst
> update ssl issue

- docs/kubernetes/kctlr-k8s-as3.rst
Add some additional language and error message regarding CIS and SSL validation.
> Update SSL language

- docs/kubernetes/kctlr-k8s-as3.rst
A table fix and language update.
> a few modifications

- docs/kubernetes/kctlr-k8s-as3.rst
Update table alignment and some language modifications.
> A few updates

- docs/kubernetes/kctlr-k8s-as3.rst
> Update insecure option

- docs/kubernetes/kctlr-k8s-as3.rst
> add partition section

- docs/kubernetes/kctlr-use-bigip-k8s.rst
There was no mention of requiring TMSH access or logging into tmsh.
> Add TMSH command

- docs/conf.py
- docs/kubernetes/kctlr-use-bigip-k8s.rst
This is the first release of CIS. Dev doesn't want a version yet.
> Removing v2 from release

- docs/conf.py
- docs/kubernetes/config_examples/f5-kctlr-bigip-node.yaml
- docs/kubernetes/kctlr-use-bigip-k8s.rst
> Fix incorrect Node IP address

- docs/conf.py
- docs/kubernetes/index.rst
> update partitions note

- docs/kubernetes/kctlr-use-bigip-k8s.rst
> Update subnet mask

- docs/kubernetes/index.rst
Rearrange a few of the sections to have the overview, installation and upgrade first, and user guides later.
> rearrange sections

- docs/conf.py
- docs/kubernetes/index.rst
Add supporting links in .conf.py
> add Features Section

- docs/kubernetes/index.rst
> grammar fix

- docs/kubernetes/index.rst
Modify / Shorten a few additional headers.
> Modify headers

- docs/kubernetes/index.rst
> fix broken link

- docs/kubernetes/index.rst
Somehow the AWS configuration has rolled backwards with the recent update. Making a small change to try to get these back into sync.
> Language change

- docs/kubernetes/kctlr-as3-cert-trust.rst
> add note - private IP

- docs/kubernetes/kctlr-k8s-as3.rst
> reference new delete procedure

- docs/kubernetes/config_examples/f5-as3-blank-example.yaml
- docs/kubernetes/kctlr-as3-delete-configmap.rst
> add newline

- docs/kubernetes/kctlr-k8s-as3-use-1.rst
> scale image

- docs/kubernetes/kctlr-k8s-as3-use-1.rst
- docs/kubernetes/kctlr-k8s-as3.rst
> Add ConfigMap section

- docs/kubernetes/config_examples/f5-hello-world-web-deployment.yaml
- docs/kubernetes/kctlr-k8s-as3-use-1.rst
> Add deployment example

- docs/kubernetes/config_examples/f5-hello-world-as3-configmap.yaml
- docs/kubernetes/config_examples/f5-hello-world-web-deployment.yaml
- docs/kubernetes/kctlr-k8s-as3-use-1.rst
> Add final configmap ex

- docs/kubernetes/kctlr-k8s-as3-use-1.rst
> Fix important

- docs/kubernetes/kctlr-k8s-as3-use-1.rst
> correct steps

- docs/kubernetes/index.rst
Reverts F5Networks/f5-ci-docs#656
> Revert "Add use case"

- docs/openshift/config_examples/f5-kctlr-openshift-hostsubnet.yaml
- docs/openshift/kctlr-use-bigip-openshift.rst
Make hostname consistent throughout doc and configmap example.
> modify big-ip-01 hostname

- .travis.yml
- scripts/deploy-docs.sh
- scripts/docker-docs.sh
Adding coveo search back in after modifying f5.css and f5-theme.css references.
> coveo back in

- docs/_static/reuse/kctlr-openshift-deployment-note.rst
- docs/openshift/kctlr-use-as3-backend.rst
New guide for OpenShif AS3 orchestration v1.10.
> new as3 1.10 use

- docs/openshift/kctlr-use-as3-backend.rst
> modify section/subsection

- docs/README.rst
agent
manage-ingress
----------
----------
@<reviewer_id>
WIP #<issueid>
...
> Add two new Configuration Parameters

- docs/f5-k8s-ingress-kube-annotate.yaml
- docs/index.rst
- docs/kubernetes/config_examples/f5-k8s-ingress-annotation.yaml
- docs/kubernetes/config_examples/f5-k8s-ingress-kube-annotate.yaml
- docs/kubernetes/flannel-bigip-info.rst
- docs/kubernetes/index.rst
- docs/kubernetes/kctlr-app-install.rst
- docs/kubernetes/kctlr-create-service-vs.rst
- docs/kubernetes/kctlr-ingress.rst
- docs/kubernetes/kctlr-k8s-as3.rst
- docs/kubernetes/kctlr-manage-bigip-objects.rst
- docs/kubernetes/kctlr-managed-objects.rst
- docs/kubernetes/kctlr-use-bigip-k8s.rst
- docs/master_toc.rst
- docs/openshift/kctlr-use-as3-backend.rst
Adding some next steps and rearranging some content.
> Add some next steps

- docs/openshift/kctlr-use-as3-backend.rst
Added CIS rel v1.11 documentation
Primary reviewers:
@mdditt2000 @kkinch @ssurenr
> CIS v1.11 User documentation Updates
